### ISSUE TITLE
Error Deploy Shuttle 

### ISSUE THREAD

**Issue by Atticus64** [graphul-rs/graphul#14]
**Describe the bug**
I'll try the example of the documentation about how to deploy graphul in shuttle
Version of Graphul 0.4.5

**To Reproduce**
1. Clone my repository on [repo](https://github.com/Atticus64/graphul-server)
2. Build the project
3. Try to deploy
4. Get the next error

**Expected behavior**
I expect to succesfully deploiment but a savage error appears

**Screenshots**
![image](https://user-images.githubusercontent.com/92958760/221393308-623e5613-fae0-4a8b-90eb-87531eb04e8c.png)

**Desktop**
 - OS: Windows 10
 - Browser brave

**Comment by SamuelBonilla** [comment]
Hi @Atticus64 , Graphul 0.4.5 does not support shuttle, shuttle support starts in version 0.4.6

please try to use the latest version Graphul v0.5.5

happy coding :)
