### ISSUE TITLE
How to do redirects?

### ISSUE THREAD

**Issue by andreapavoni** [graphul-rs/graphul#6]
I was wondering if there's a way to redirect requests rather than replying with `HtmlTemplate` or `Json`.

Thanks in advance, and congratulations for this interesting project!

**Comment by SamuelBonilla** [comment]
@andreapavoni  Sure, you can try with

```rust
use graphul::{Graphul, http::{response::Redirect, Methods}, Context };

#[tokio::main]
async fn main() {
    let mut app = Graphul::new();

    app.get("/", || async {
        // Redirect::temporary(uri) Create a new Redirect that uses a 307 Temporary Redirect status code.
        // Redirect::permanent(uri) Create a new Redirect that uses a 308 Permanent Redirect status code.
        Redirect::to("/hi/samuel") // Create a new Redirect that uses a 303 See Other status code.
    });

    app.get("/hi/:name", |c: Context| async move {
        format!("hello, {}", c.params("name"))
    });

    app.run("127.0.0.1:8000").await;
}
```

**Comment by andreapavoni** [comment]
Thank you! It somewhat works, but I still have some problem in using it in practice. I need to check authentication when loading a page, if it's not authenticated, the user should be redirected on another page. I tried:

* inside the handler, I call the redirect if not authenticated, or render a template -> I get a compiler error:

```
expected struct `Redirect`, found struct `HtmlTemplate`
```

* using a middleware: redirect if not authenticated, or call `next.run(request).await` -> I a similar compiler error:

```
expected struct `http::response::Response`, found struct `Redirect`
```

I'm mostly a Rust beginner and maybe I'm just doing some silly mistake or overlooking some detail

**Comment by SamuelBonilla** [comment]
Hmm 🤔,  Could you share some example code to try to reproduce the error?

**Comment by SamuelBonilla** [comment]
@andreapavoni try with this example, you need to use .into_response

```rust
use graphul::{Graphul, http::{response::Redirect, Methods}, Context, IntoResponse };

#[tokio::main]
async fn main() {
    let mut app = Graphul::new();

    // ?redirect=true
    app.get("/", |c: Context| async move {
        // Redirect::temporary(uri) Create a new Redirect that uses a 307 Temporary Redirect status code.
        // Redirect::permanent(uri) Create a new Redirect that uses a 308 Permanent Redirect status code.
        if c.query("redirect") == "true" {
            return Redirect::to("/hi/samuel").into_response() ; // Create a new Redirect that uses a 303 See Other status code.
        }
        "index".into_response()
    });

    app.get("/hi/:name", |c: Context| async move {
        format!("hello, {}", c.params("name"))
    });

    app.run("127.0.0.1:8000").await;
}
```

**Comment by andreapavoni** [comment]
Sure, here's an example of my use case (the real code is really messed with other stuff as of now):

```rust
app.get("/", |_c: Context| async move {
    let authenticated = false;
    if !authenticated {
        Redirect::to("/login")
    } else {
        let template = HomeTemplate {
            message: "Hello".to_string(),
        };
        HtmlTemplate(template)
    }
});
  ```
  
  As you can see, I'm trying to redirect the user, rather than showing the template. The other case using a middleware is similar:
  
```rust
async fn check_user_is_authenticated(request: Req, next: Next) -> Response {
    let authenticated = false;
    if !authenticated {
        return Redirect::to("/login");
    } else {
        next.run(request).await
    }
}
```

The error is similar, in both cases the compiler complains about mismatching return types. Thank you for your help!

**Comment by SamuelBonilla** [comment]
like my previous comment try with .into_reponse, this is an implementation for your example code

###  middleware

```rust
async fn check_user_is_authenticated(request: Req, next: Next) -> Response {
    let authenticated = false;
    if !authenticated {
        return Redirect::to("/login").into_response() ;
    } else {
        next.run(request).await
    }
}
```

### Handler

```rust
app.get("/", |_c: Context| async move {
    let authenticated = false;
    if !authenticated {
        Redirect::to("/login").into_response()
    } else {
        let template = HomeTemplate {
            message: "Hello".to_string(),
        };
        HtmlTemplate(template).into_response()
    }
});
```

**Comment by andreapavoni** [comment]
hi @SamuelBonilla thank you very much, it works! My bad I've only tried `into()` and forgetting about the `into_response()` function.

I think this issue might be closed. Doo you think it might be useful to add this info in README/doc? If so, I might open a PR for that :)
