### ISSUE TITLE
Middleware for individual/group routes

### ISSUE THREAD

**Issue by andreapavoni** [graphul-rs/graphul#7]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it's already built-in, but I was wondering if it's possible to associate middlewares to an individual (or a group of) routes.

**Describe the solution you'd like**
I'd like to define middlewares that can be usable on individual/group routes rather than setting them up globally.

**Describe alternatives you've considered**
None at the moment

**Additional context**
A common use case (and the one which I stumbled upon recently) is about routes that require authentication along with the ones that don't. So for example, you have a bunch of _public_ routes (eg: `/*`) and another bunch of _private_ ones (eg: `/admin/*`). If I setup a middleware that checks authentication (and eventually redirects to a login page if the client is not authenticated) means that it'll act even to the _public_ routes (and it'll create an endless loop which redirects to the login page).

What do you think? Thanks in advance for any feedback.

**Comment by SamuelBonilla** [comment]
When you add middleware with app.middleware all previously added routes will be wrapped in the middleware. Generally speaking, this results in middleware being executed from bottom to top.

try with:

``` rust
use graphul::{http::{Methods, response::{Response, Redirect}}, Graphul, middleware::{self, Next}, Req, IntoResponse};


async fn check_user_is_authenticated(request: Req, next: Next) -> Response {
    let authenticated = false;
    if !authenticated {
        return Redirect::to("/login").into_response() ;
    } 
    next.run(request).await
}

#[tokio::main]
async fn main() {
    let mut app = Graphul::new();

    app.get("/", || async {
        "protected index route"
    });
    app.middleware(middleware::from_fn(check_user_is_authenticated));

    // routes out of the scope of the middleware
    app.get("/login", || async {
        "Login page"
    });

    app.run("127.0.0.1:8000").await;
}
```


based on your feedback we will support middleware through groups

Future API v0.5.0:

``` rust
#[tokio::main]
async fn main() {
    let mut app = Graphul::new();

    let mut admin = app.group("admin");

    // /admin
    admin.get("/", || async {
        "protected index route"
    });

    app.get("/login", || async {
        "Login page"
    });

    // add middleware to a specific group of routes ( 1 or n  groups)
    app.middleware_groups(["admin"], my_middleware);

    app.run("127.0.0.1:8000").await;
}
```

**Comment by andreapavoni** [comment]
Wow, that's interesting for the first part. And thank you for the announced new features!
