### ISSUE TITLE
Add Comparison & benchmarks to Readme

### ISSUE THREAD

**Issue by frederikhors** [graphul-rs/graphul#8]
Thanks for your work.

Can I ask you the advantages over other routers? (Let's say [`axum`](https://github.com/tokio-rs/axum) or [`poem`](https://github.com/poem-web/poem)?)

I think the famous space called "Comparison" is missing in the Readme.

And benchmarks wouldn't be bad either.

:smile:

**Comment by SamuelBonilla** [comment]
Ok Thanks, I’m working on it

**Comment by SamuelBonilla** [comment]
As you Can see on the website https://graphul-rs.github.io/

The advantages over other Rust framework is the clear API and friendly syntax, it feels like writing a microservices in Python or expressjs ( nodejs ),
and you can have the same performance of hyper

Note: Must ( 99%) of the rust web framework are written on top of hyper
